version: "3"

services:
  app:
    container_name: gin-app-book
    build:
      target: builder
      context: .
    command: air .
    ports:
      - 8080:8080
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`localhost`) && PathPrefix(`/api`)"
    volumes:
      - .:/go/src/app
    depends_on:
      - db
      - reverse-proxy
    networks:
      - gin-app
    env_file:
      - .env

  db:
    build: .docker/postgres
    container_name: gin-db-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - gin-app
    env_file:
      - .env

  reverse-proxy:
    image: traefik:v2.0
    container_name: traefik-gin
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gin-app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - gin-app
    restart: unless-stopped
    env_file:
      - .env

  # mysql:
  #   image: mysql:5.7
  #   container_name: full_db_mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_HOST=${DB_HOST}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - fullstack

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   depends_on:
  #     - fullstack-mysql
  #   environment:
  #     - PMA_HOST=postgres
  #     - PMA_USER=${DB_USER}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - fullstack

volumes:
  api:
  database_postgres:

networks:
  gin-app:
    driver: bridge
